server:
  port: 8080
spring:
  application:
    name: user-thrift-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

