server:
  port: 7911

spring:
  application:
    name: user-thrift-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_user?useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

