server:
  port: 8082


thrift:
  user:
    ip: 127.0.0.1
    port: 7911

spring:
  application:
    name: user-edge-service
  redis:
    #数据库主机
    host: 127.0.0.1
    #数据库端口
    port: 6379
    #连接超时时间
    timeout: 3000
    #数据库索引（默认为0）
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制），默认8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认-1
        max-wait: -1ms
        # 连接池中的最大空闲连接，默认8
        max-idle: 8
        # 连接池中的最小空闲连接，默认0
        min-idle: 0
  cache:
    redis:
      # 设置缓存默认超过期时间为30秒
      time-to-live: 30


